name: Setup Homebrew toolchain
inputs:
  dependency-list:
    type: string
    required: true
    description: "Path to a text file containing homebrew dependencies, one per line."
    default: "${GITHUB_WORKSPACE}/.github/actions/homebrew-dependencies/build-dependencies.txt"

runs:
  using: "composite"
  steps:
    - name: Update homebrew
      run: |
        brew update
      shell: bash

    - name: Install homebrew dependencies
      run: |
        xargs brew install < ${{ inputs.dependency-list }}
      shell: bash
