import Foundation

extension MockCredential {
    /// Jane Doe mock credential generated by the DVLA mDoc Builder.
    static let janeDoe = createMock(
        for: "JaneDoeCredential",
        privateKeyHex: "7694cedd963ac024bc71adc707b38ec30297fb8091344be08d1793f4d88e0c12"
    )

    static func createMock(for resource: String, privateKeyHex: String, bundle: Bundle = .main) -> MockCredential {
        guard let url = bundle.url(forResource: resource, withExtension: "txt"),
              let base64URL = try? String(contentsOf: url).trimmingCharacters(in: .whitespacesAndNewlines) else {
            fatalError("\(resource).txt not found in bundle")
        }

        // Convert base64url to standard base64
        var base64 = base64URL
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        while base64.count % 4 != 0 { base64.append("=") }

        guard let rawCredential = Data(base64Encoded: base64) else {
            fatalError("Failed to decode \(resource) base64 data")
        }

        // 32-byte P-256 private key matching the public key in the credential's MSO
        let privateKey = Data(hexString: privateKeyHex)!

        return MockCredential(
            id: "jane-doe-mock-credential",
            displayName: "Jane Doe",
            rawCredential: rawCredential,
            privateKey: privateKey
        )
    }
}

private extension Data {
    init?(hexString: String) {
        let len = hexString.count / 2
        var data = Data(capacity: len)
        var index = hexString.startIndex
        for _ in 0..<len {
            let nextIndex = hexString.index(index, offsetBy: 2)
            guard let byte = UInt8(hexString[index..<nextIndex], radix: 16) else { return nil }
            data.append(byte)
            index = nextIndex
        }
        self = data
    }
}
