# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#
require 'securerandom'

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)
# xcode_select("/Applications/Xcode_16.4.app")

platform :ios do
  lane :clean do
    desc "Clears the system of build artifacts"

    clean_build_artifacts
    clear_derived_data
    reset_simulator_contents(os_versions: ["26.4"])
  end

  lane :test do |options|
    desc "Run Tests and Output Code Coverage"

    clear_derived_data

    run_tests(
      code_coverage: true,
      workspace: "CredentialSharing.xcworkspace",
      devices: ["iPhone 17 Pro (26.4)"],
      output_directory: './fastlane/test_output',
      result_bundle: true,
      scheme: options[:scheme],
      testplan: options[:testplan],
      xcargs: '-skipPackagePluginValidation'
    )

    slather(
      proj: "./mobile-credential-sharing-ios/mobile-credential-sharing-ios.xcodeproj",
      sonarqube_xml: true,
      workspace: "CredentialSharing.xcworkspace",
      scheme: options[:scheme],
      use_bundle_exec: true,
      output_directory: "./Fastlane/test_output/#{options[:testplan]}"
    )

    ensure reset_simulator_contents(os_versions: ["26.4"])
  end

  lane :sonarCloudScan do |options|
    desc "Perform SonarCloud scan. Requires output from 'test' lane."
    report_prefix = "#{options[:workspace]}/Fastlane/test_output"

    report_files = [
      "Contract",
      "Simulator",
      "Unit"
    ]
      .map { |test_plan_prefix| "#{test_plan_prefix}TestPlan" }
      .map { |test_plan| "#{report_prefix}/#{test_plan}/sonarqube-generic-coverage.xml" }
      .join(",")

    runner_arguments = [
      "sonar.projectBaseDir=#{options[:workspace]}",
      "sonar.c.file.suffixes=-",
      "sonar.cpp.file.suffixes=-",
      "sonar.objc.file.suffixes=-",
      "sonar.pullrequest.provider=github",
      "sonar.swift.coverage.reportpaths=#{report_files}",
    ].map { |property| "-D#{property}"}
    .join(" ")

    if options.has_key?(:pr_number) then
      sonar(
        project_version: "1.0",
        project_language: "swift",
        sonar_runner_args: runner_arguments,
        pull_request_branch: options[:source_branch],
        pull_request_base: options[:target_branch],
        pull_request_key: options[:pr_number],
        sonar_token: options[:sonar_token],
        sonar_url: "https://sonarcloud.io"
      )
    else
      sonar(
        project_version: "1.0",
        project_language: "swift",
        sonar_runner_args: runner_arguments,
        sonar_token: options[:sonar_token],
        sonar_url: "https://sonarcloud.io"
      )
    end
  end

  lane :prerelease do |options|
    desc "Push a new beta build to TestFlight"
    clear_derived_data
    
    password = SecureRandom.hex

    begin
      
      create_keychain(
        name: "signing_temp",
        password: password,
        timeout: 1800,
        unlock: true
      )

      import_certificate(
        certificate_path: options[:certificate_path],
        certificate_password: options[:certificate_password],
        keychain_name: 'signing_temp',
        keychain_password: password,
        log_output: true
      )

      app_store_connect_api_key(
        key_id: "LK43S2LHBT",
        issuer_id: "053ce927-96a7-4d15-8176-6c282fd0b594",
        key_filepath: options[:apikey_path]
      )

      profile_name = "GOV.UK Wallet Sharing Test App"
      app_identifier = "uk.gov.onelogin.sharing.testapp"

      get_provisioning_profile(
        provisioning_name: profile_name,
        app_identifier: app_identifier,
        readonly: true
      )

      version = get_version_number(xcodeproj: "mobile-credential-sharing-ios/mobile-credential-sharing-ios.xcodeproj")

      build_number = latest_testflight_build_number(
        app_identifier: app_identifier,
        version: version
      ) + 1

      increment_build_number(
        xcodeproj: "mobile-credential-sharing-ios/mobile-credential-sharing-ios.xcodeproj",
        build_number: build_number
      )

      update_code_signing_settings(
        use_automatic_signing: false,
        path: "mobile-credential-sharing-ios/mobile-credential-sharing-ios.xcodeproj",
        profile_name: profile_name,
        targets: "mobile-credential-sharing-ios",
        team_id: "N8W395F695",
        code_sign_identity: "Apple Distribution"
      )

      build_ios_app(
        scheme: "Sharing-Demo",
        output_name: "GOV.UK Sharing",
        export_method: "app-store",
        export_xcargs: '-skipPackagePluginValidation',
        xcargs: '-skipPackagePluginValidation'
      )

      begin
        upload_to_testflight(
          beta_app_description: "The CredentialSharing testflight app",
          distribute_external: false,
          changelog: last_git_commit[:message],
          reject_build_waiting_for_review: false,
          submit_beta_review: false
        )
      end
    ensure
      reset_simulator_contents(os_versions: ["26.4"])
      delete_keychain(name: "signing_temp")
    end
  end
end
