#!/usr/bin/env bash

# Example usage:
# `./scripts/test "UnitTestPlan"`

TEST_PLAN="${1}"

bundle exec fastlane test scheme:"Sharing-Demo" \
    sonar_token:"${SONAR_TOKEN}" \
    workspace:"${WORKSPACE}" \
    source_branch:"${HEAD_REF}" \
    target_branch:"${BASE_REF}" \
    testplan:"${TEST_PLAN}" \
    pr_number:"${PR_NUMBER}"
