name: Setup Ruby toolchain
inputs:
  version:
    type: string
    required: true
    description: "The version of ruby to download / use."
    default: "3.2.2"

runs:
  using: "composite"
  steps:
    - name: Update homebrew
      run: |
        brew update

    - name: Install homebrew dependencies
      run: |
        xargs brew install < "${GITHUB_WORKSPACE}/.github/actions/homebrew-dependencies/dependencies.txt"
