name: iOS Pull Request

on:
  workflow_call:

concurrency:
  group: linting-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-pr-name:
    name: Validate Pull Request Name
    runs-on: macos-26
    steps:
      - name: Validate PR name
        uses: Oliver-Binns/Versioning@26996c64bce96a4bd238cc9a8fcb34cd9c2f9dc8 # pin@v1.5.2
        with:
          ACTION_TYPE: 'Validate'

  swift-lint:
    name: Swiftlint
    runs-on: macos-26
    timeout-minutes: 2
    steps:
      - name: Add Path Globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Homebrew
        uses: ./.github/actions/homebrew-dependencies
        with:
          dependency-list: "${GITHUB_WORKSPACE}/.github/actions/homebrew-dependencies/lint-dependencies.txt"

      - name: Run Linter
        run: |
          swiftlint --strict
        shell: bash
