name: iOS Quality Report

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  linting-workflow:
    name: "Linting (main)"
    uses: ./.github/workflows/linting.yml
    secrets: inherit

  create-test-build:
    name: Create test build
    uses: ./.github/workflows/build-without-test.yml
    secrets: inherit

  testing-workflow:
    name: "Testing (main)"
    needs: [ create-test-build ]
    uses: ./.github/workflows/testing.yml
    secrets: inherit

  sonar-scan:
    name: "SonarCloud scan (main)"
    needs: [ testing-workflow ]
    runs-on: macos-26
    timeout-minutes: 28
    steps:
      - name: Add "/usr/local/bin" to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Setup Homebrew
        uses: ./.github/actions/homebrew-dependencies

      - name: Setup Ruby
        uses: ruby/setup-ruby@d45b1a4e94b71acab930e56e79c6aa188764e7f9 # v1.316.0
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Download test coverage artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c #v8.0.1
        with:
          pattern: "*-test-coverage"
          merge-multiple: true

      # Create a comma-separated list of all the available 'sonarqube-generic-coverage.xml' files.
      - name: Find sonar coverage data
        run: |
          echo "COVERAGE_FILES=$(find $(pwd) -type f -name "sonarqube-generic-coverage.xml" | paste -sd "," -)" >> $GITHUB_ENV
        shell: bash

      - name: Perform sonar scan via GitHub action
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            "-Dsonar.c.file.suffixes=-"
            "-Dsonar.coverageReportPaths=${COVERAGE_FILES}"
            "-Dsonar.cpp.file.suffixes=-"
            "-Dsonar.host.url=https://sonarcloud.io"
            "-Dsonar.objc.file.suffixes=-"
            "-Dsonar.projectBaseDir=."
            "-Dsonar.projectVersion=1.0"
